Import('env', 'libs')

env = env.Clone()
deps = ['devices', 'SPI', 'arduino']
env.Append(LIBS=[libs[dep] for dep in deps])

obj = env.StaticObject('test_dac.cpp')
hex_ = env.HexObject(obj)
Return('hex_')
