Import('env', 'libs', 'incs')

env = env.Clone()

libnames = ['arduino']

incpaths = list(set([incs[n] for n in libnames]))
incpaths.append('utility')
env.Append(CPPPATH=incpaths)

libnames = [name for name in libnames if libs[name] is not None]

libnodes = [libs[name] for name in libnames]
env.Append(LIBS=libnodes)

libpaths = [env.GetBuildPath(name) for name in libnames]
env.Append(LIBPATH=libpaths)

twi = SConscript('utility/SConscript', exports=['env', 'libs', 'incs'])
Wire = env.StaticLibrary('Wire', ['Wire.cpp', twi])[0]

Return('Wire')
