Import('env', 'libs')

import os

env.Append(CPPPATH=[env.Dir('.')])

env = env.Clone()
env.Append(libs=[libs['arduino']])
env.Append(CPPPATH='utility')

twi = env.Glob(os.path.join('utility', '*.c'))
lib = env.StaticLibrary('Wire', ['Wire.cpp', twi])[0]

Return('lib')
