Import('env', 'libs', 'incs')

env = env.Clone()

libnames = ['arduino']

incpaths = list(set([incs[n] for n in libnames]))
env.Append(CPPPATH=incpaths)

elshield = env.StaticLibrary('elshield', ['elshield.cpp'])[0]

Return('elshield')
