Import('env', 'libs', 'incs')

env = env.Clone()
env.Replace(CC='avr-gcc')

libnames = ['arduino']

incpaths = list(set([incs[n] for n in libnames]))
env.Append(CPPPATH=incpaths)

libnames = [name for name in libnames if libs[name] is not None]

libnodes = [libs[name] for name in libnames]
env.Append(LIBS=libnodes)

libpaths = [env.GetBuildPath(name) for name in libnames]
env.Append(LIBPATH=libpaths)

twi = env.StaticLibrary('twi', 'twi.c')[0]

Return('twi')
