Import('env', 'libs', 'incs')

env = env.Clone()
libnames = ['arduino']

incpaths = list(set([incs[n] for n in libnames]))
env.Append(CPPPATH=incpaths)

libnames = [name for name in libnames if libs[name] is not None]

libnodes = [libs[name] for name in libnames]
env.Append(LIBS=libnodes)

libpaths = [env.GetBuildPath(name) for name in libnames]
env.Append(LIBPATH=libpaths)

obj = env.StaticObject(target='serial.o', source=['serial.c'])
elf = env.Program(target='serial.elf', source=[obj])
objcopy_cmd = "avr-objcopy -O ihex -R .eeprom $SOURCE $TARGET"
hex_ = env.Command('serial.hex', elf, objcopy_cmd)

Return('hex_')
