Import('env', 'libs', 'incs')

env = env.Clone()
libnames = ['arduino', 'haar']

incpaths = list(set([incs[n] for n in libnames]))
env.Append(CPPPATH=incpaths)

libnames = [name for name in libnames if libs[name] is not None]

libnodes = [libs[name] for name in libnames]
env.Append(LIBS=libnodes)

obj = env.StaticObject(target='test_haar.o', source=['test_haar.c'])
elf = env.Program(target='test_haar.elf', source=[obj])
objcopy_cmd = "avr-objcopy -O ihex -R .eeprom $SOURCE $TARGET"
hex_ = env.Command('test_haar.hex', elf, objcopy_cmd)

Return('hex_')
