Import('env', 'libs')

env = env.Clone()
deps = ['neopixel', 'devices', 'SPI', 'TimerOne', 'arduino', 'FHT', 'AGC']
env.Append(LIBS=[libs[dep] for dep in deps])

obj = env.StaticObject('test_adc.cpp')
hex_ = env.HexObject(obj)
Return('hex_')
