Import('env')
dirs = [
    'arduino',
    'SPI',
    'Wire',
    'TimerOne',
    'SoftwareSerial',
    'codec',
    'elshield',
    'haar',
    'neopixel',
    ]
libs = dict()
incs = dict()
for dir_ in dirs:
    script = dir_+'/SConscript'
    libs[dir_] = SConscript(script, exports=['env', 'libs', 'incs'])
    incs[dir_] = Dir(dir_)
Return('libs', 'incs')
