Import('env', 'libs', 'incs')
dirs = ['haar', 'cutest', 'codec']

for dir_ in dirs:
    script = dir_+'/SConscript'
    libs[dir_] = SConscript(script, exports=['env', 'libs', 'incs'])
    incs[dir_] = Dir(dir_)
