Import('env')
dirs = ['haar', 'cutest']
scripts = [dir_+'/SConscript' for dir_ in dirs]
libs = [SConscript(s, exports=['env']) for s in scripts]
libs = dict(zip(dirs, libs))
incs = {dir_: Dir(dir_) for dir_ in dirs}
Return('libs', 'incs')
