Import('env', 'libs', 'incs')
import os
dirs = next(os.walk('.'))[1]
scripts = [dir_+'/SConscript' for dir_ in dirs]
apps = [SConscript(s, exports=['env', 'libs', 'incs']) for s in scripts]
apps = dict(zip(dirs, apps))
Return('apps')
