Import('env', 'libs', 'incs')
dirs = ['serial', 'test_haar']
scripts = [dir_+'/SConscript' for dir_ in dirs]
apps = [SConscript(s, exports=['env', 'libs', 'incs']) for s in scripts]
apps = dict(zip(dirs, apps))
Return('apps')
