Import('env', 'libs')

env.Append(CPPPATH=[env.Dir('include')])

env = env.Clone()

deps = ['arduino', 'SPI', 'Wire']
env.Append(libs=[libs[name] for name in deps])

lib = env.StaticLibrary('devices', env.Glob('lib/*.cpp'))[0]

Return('lib')
