Import('env', 'libs')

env = env.Clone()
deps = ['TimerOne', 'arduino']
env.Append(LIBS=[libs[dep] for dep in deps])

obj = env.StaticObject('test_dimmer.cpp')
hex_ = env.HexObject(obj)
Return('hex_')
